services:
  api:
    container_name: conecta_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app            # hot-reload de código em dev (opcional)
      # - ./instance:/app/instance  # só mantenha se realmente usar essa pasta
    command: >
      sh -c "
        python -c 'import importlib; importlib.import_module(\"wsgi\")' &&
        exec gunicorn --bind :8080 --workers 2 --threads 4 --timeout 120 wsgi:app
      "
    restart: unless-stopped