services:
  api:
    container_name: conecta_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "
        echo '➡️ Rodando migrations...' &&
        python -m flask --app wsgi:app db upgrade || true &&
        echo '✅ Migrations concluídas, iniciando Gunicorn...' &&
        exec gunicorn --bind :8080 --workers 2 --threads 4 --timeout 120 wsgi:app
      "
    restart: unless-stopped