"""autogen

Revision ID: 4aa4a87fcf65
Revises: b76b09c881e0
Create Date: 2025-10-18 14:50:46.673889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa4a87fcf65'
down_revision = 'b76b09c881e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
        batch_op.create_unique_constraint(None, ['uuid'])
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('name')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
