"""autogen

Revision ID: 62b2cd1b9362
Revises: 4aa4a87fcf65
Create Date: 2025-10-19 15:17:20.843782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b2cd1b9362'
down_revision = '4aa4a87fcf65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # drop index
        batch_op.drop_index(batch_op.f('ux_users_uuid'))
        # create unique constraint with explicit name
        batch_op.create_unique_constraint('uq_users_uuid', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # drop constraint with the same name used above
        batch_op.drop_constraint('uq_users_uuid', type_='unique')
        # recreate index
        batch_op.create_index(batch_op.f('ux_users_uuid'), ['uuid'], unique=1)
    # ### end Alembic commands ###